#!/bin/bash

## Please specify AWS_REGION and AWS_PROFILE
if [[ "$AWS_REGION" == "" ]]; then
	echo "Please specify AWS_REGION"
	exit 1
fi

if [[ "$AWS_PROFILE" == "" ]]; then
	echo "Please specify AWS_PROFILE"
	exit 1
fi

aws ec2 describe-instances --region $AWS_REGION --query 'Reservations[*].Instances[*].[InstanceId,InstanceType,State.Name,Tags[?Key==`Name`].Value|[0],PrivateIpAddress,PublicIpAddress]' --output table --profile $AWS_PROFILE
