#!/bin/bash

SID=$1

if [[ $SID == "" ]]; then
  echo "1st argument is empty. Please provide secret id.."
  exit 1
fi

aws secretsmanager get-secret-value --query SecretString --region $AWS_REGION --output text --profile $AWS_PROFILE --secret-id $SID