#!/usr/bin/env python3

import sys
import json
import yaml

#print(yaml.dump(json.load(open(sys.argv[1])), default_flow_style=False))

filename = sys.argv[1]
fileobj = open(filename, 'r')
json_content = json.load(fileobj)
print(yaml.dump(json_content, default_flow_style=False))
