#!/bin/bash

INSTANCE_ID=$1

if [ -z "$INSTANCE_ID" ]; then
	echo "Usage: $0 <instance_id>"
	exit 1
fi

aws ec2 stop-instances --instance-ids $INSTANCE_ID --profile $AWS_PROFILE
if [ $? -eq 0 ]; then
	echo "Instance $INSTANCE_ID stopped"
else
	echo "Failed to stop instance $INSTANCE_ID"
	exit 1
fi
