#!/usr/bin/env python3
""" This Script helps in creating InMobi JIRA ticket """
""" Author: Anto Daniel """

from jira.client import JIRA
import argparse
import logging
import os
import urllib3

urllib3.disable_warnings()
LOGGER_NAME = 'smarsh:jira'
# Set up logging
log = logging.Logger(LOGGER_NAME, logging.INFO)
loghandler = logging.StreamHandler()
loghandler.setFormatter(logging.Formatter
                        ('%(name)s: %(levelname)s: %(message)s'))
log.addHandler(loghandler)

### Get jira credentials from environment variables

email_id = os.environ.get('JIRA_EMAIL')
jira_api_token = os.environ.get('JIRA_API_TOKEN')
server = os.environ.get('JIRA_SERVER')

## Example: jira_create -p SAAS -s "MongoDB bosh release, need to make sure current node does not have any replication lag with primary" -d "TBP" -t Task -c "Paas"    

class CreateJIRA:
    """ Main Class """

    def __init__(self):
        """ Initial Variables """

        self.emailid = email_id
        options = {'server': server, 'verify': False}
        api_token = jira_api_token
        self.jira = JIRA(options, basic_auth=(email_id, api_token))

    def create_jira(self, args):
        """ With previous method details, creats jira ticket """

        issue = self.jira.create_issue(project={'key': ""+args.project+""}, 
                summary=""+args.summary+"",
                #origin=""+args.origin+"",
                description=""+args.description+"",
                customfield_13631={'value': 'PaaS Data Services'},
                #assignee={'name': 'anto.paul',
                #          'emailAddress':
                #          'anto.paul@smarsh.com'},
                issuetype={'name': ""+args.type+""},
                #components=[{'name': ""+args.component+""},],
            )
        log.info('JIRA Ticket ID: %s created' % issue)
#        os.system("xdg-open https://jira.corp.domain.com/browse/"+issue.__str__())


def main():

    parser = argparse.ArgumentParser("Command Line Interface for JIRA")
    parser.add_argument(
        '--debug',
        action='store_true',
        default=False,
        help='print debugging information')

    parser.add_argument("-p", "--project", help="Please specify ProjectType",
                        required=True)
    parser.add_argument("-s", "--summary", help="Please specify summary",
                        required=True)
    parser.add_argument("-d", "--description", help="Description of the issue",
                        required=True)
    parser.add_argument("-c", "--component", default='GRID Ops', help="Components of the issue",
                        required=False)
    parser.add_argument("-t", "--type", default='Nagios Alerts', help="Issue Type",
                        required=False)

 #   parser.add_argument("--origin", help="origin of the ticket. ex:-Ops/Production",
 #                       required=True)
    args = parser.parse_args()
    instance = CreateJIRA()
    instance.create_jira(args)

    if args.debug:
        log.setLevel(logging.DEBUG)

    log.debug('Arguments: %s', args)


if __name__ == "__main__":
    main()
