name: Install AWS Cli V2

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: 2
          verbose: false
          arch: amd64
          binddir: "/usr/local/bin"
          installrootdir: "/usr/local"
          rootdir: ""
          workdir: ""

